openapi: "3.0.0"
info:
  title: learn express and swagger  - learncodeonline
  description: LCO - a course segment about writing docs
  version: 1.1.0
  contact:
    email: hitesh@google.com
    url: "https://lco.dev"

# servers:
#   - url: "https://localhost:400/api/v1"
#     description: for local host - secure
#   - url: "http://localhost:400/api/v1"
#     description: for local host - regular      

servers:
  - url: "{protocol}://localhost:400/api/{version}"
    description: "for local host"
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BeareAuth:
      type: http
      scheme: bearer

paths:
  /lco:
    get:
      tags:
        - string
      summary: returns a greet msg from LCO
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error          

  /lcoobject:
    get:
      tags:
        - object
      summary: returns a unique
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error          

